name: "PR checks"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  check-build:
    name: "Build image"
    runs-on: ubuntu-latest

    container:
      image: quay.io/podman/stable:v5.8.4@sha256:3b9f8367aa3e71b88914ea391f083fccc58c133d07b72f506e7104072ae4a6ed
      options: --privileged

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Build image"
        run: |
          podman build --no-hosts --no-hostname .
