name: "PR checks"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  check-build:
    name: "Build image"
    runs-on: ubuntu-latest

    container:
      image: quay.io/podman/stable:v5.8.4@sha256:892ad559351bcda730529b256a4cdb96ecbbbbbcd3bb68e404542874f5b8ddc5
      options: --privileged

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: "Build image"
        run: |
          podman build --no-hosts --no-hostname .
